<div id="about">
    <h1 class="largeTitle">About</h1>

    <h1 class="title">Rules</h1>
    <div class="container">
        Any and all modifications of the game that change the physics or controls in any way is strictly banned, with the exception of some console commands, see below.
        <br>
        In particular, note that this means that changing the server tickrate is forbidden, as well as any usage of the 'give' command.
        <br><br>
        Futhermore, all top 5 scores obtained after May 11th, 2017 require proof in the form of a demo or a video. If no sufficient proof can be provided, the score will be removed.
    </div>

    <h1 class="title">Console commands</h1>
    <h2 class="subtitle">Gameplay</h2>
    <div class="container smallContainer">
        <table class="table table-condensed">
            <tr>
                <td>sv_player_funnel_into_portals</td>
                <td>Disabling this will stop the player from curving into nearby portals when falling.</td>
            </tr>
            <tr>
                <td>developer</td>
                <td>Allows you to move as soon as the chamber loads instead of being stuck for ~0.5 seconds.<br>
                    We allow this command because the same effect can be achieved by loading the chamber
                    from the main menu instead of restarting it.</td>
            </tr>
            <tr>
                <td style="max-width: 260px">"mat_ambient_light_b 0.1; mat_ambient_light_r 0.1; mat_ambient_light_g 0.1;"</td>
                <td>Turns off the game's lighting and allows you to see in the dark. This is useful in Turret Factory. <br>
                    We allow this command because it levels the playing field for players having displays with limited brightness.
                </td>
            </tr>
            <tr>
                <td>bind [KEY] taunt</td>
                <td>Binds a key to taunt while midair in cooperative. Used to skip forced animations of new gestures.</td>
            </tr>
        </table>
    </div>
    <h2 class="subtitle">Recording demos</h2>
    <div class="container">
        <table class="table table-condensed">
            <tr>
                <td style="min-width: 260px">record [name]</td>
                <td>Starts recording the player's inputs generating a demo (.dem) file.</td>
            </tr>
            <tr>
                <td>stop</td>
                <td>Stops the current demo recording.</td>
            </tr>
            <tr>
                <td>playdemo [name]</td>
                <td>Replays a recorded demo.</td>
            </tr>
            <tr>
            <td>bind [KEY] "stop; restart_level"</td>
                <td> Binds a key to stop the current demo and restart the chamber to start a new run. This is useful, because
                restarting a chamber while recording to a demo called "demo" will create a new demo called "demo_2".
                A side effect of this is that the chamber loads slightly slower, and because of this you lose about 0.40 seconds. This is prevented by stopping the demo before restarting.
                </td>
            </tr>
            <tr>
                <td>bind W "+forward; +remote_view"</td>
                <td>Binds your W key to permanently show your partner view while playing cooperative.
                This way you don't need to toggle the partner view manually every time the chamber is restarted.
                </td>
            </tr>
            <tr>
                <td>cl_enable_remote_splitscreen</td>
                <td>Shows the partner view while replaying a cooperative demo.</td>
            </tr>
        </table>
    </div>

    <h1 class="title">Videos</h1>
    <div class="container">
        A popular tool used to convert demo files to nicely looking smooth videos is  <a href="https://code.google.com/archive/p/srcdemo2">SrcDemo<sup>2</sup></a>.
    </div>

    <h1 class="title">Point calculation</h1>
    <div class="container">
        Currently, the top <?=Leaderboard::numTrackedPlayerRanks?> times are tracked for each map.
        A player's points for a specific chamber is calculated as follows:
        <style>
            table.fraction  {
                font-size: 15px;
                color: inherit;
                margin: 15px;
            }
            table.fraction td.upper_line {
                border-top:solid 1px #555555;
            }
            table.fraction {
                text-align: center;
                vertical-align: middle;
                margin-top:0.5em; margin-bottom:0.5em; line-height: 1.6em;
            }
        </style>
        <table class="fraction" cellpadding="0" cellspacing="0">
            <tr>
                <td rowspan="2" nowrap="nowrap">
                    max[1,&nbsp;
                </td>
                <td nowrap="nowrap" style="font-size: 14px;">
                    (<?=Leaderboard::numTrackedPlayerRanks?> - (rank - 1))<sup>2</sup>
                </td>
                <td rowspan="2" nowrap="nowrap">
                    <!-- &nbsp;× (1 + (0.025 × bonus)  -->]
                </td>
            </tr>
            <tr>
                <td class="upper_line" style="font-size: 14px;">
                    <?=Leaderboard::numTrackedPlayerRanks?>
                </td>
            </tr>
        </table>

        This gives us the following:

        <style>
            .pointTable th {
                font-weight: 500;
                color: #555;
            }
            .pointTable td, .pointTable th {
                text-align: center;
            }
            .pointTable th:first-child, .pointTable td:first-child {
                border-right: 1px solid #ddd;
            }
        </style>
        <table class="pointTable table table-condensed" style='margin-top: 20px; width: 160px'>
            <tr>
                <th>Rank</th>
                <th>Points</th>
            </tr>
            <?php foreach(array(1, 5, 10, 20, 50, 100, 150, 200) as $rank): ?>
                <tr>
                    <td><?=$rank ?></td>
                    <td><?=ceil(Leaderboard::getPoints($rank))?></td>
                </tr>
            <?php endforeach; ?>
        </table>

        Note that points are displayed as whole numbers everywhere on the site by means of simple rounding.

    </div>

    <h1 class="title">Team</h1>
    <div class="container">
        <ul>
            <?php
                $data = Database::query("SELECT profile_number, IFNULL(boardname, steamname) as playername, title, admin FROM usersnew WHERE admin = 1 OR title = 'Developer' ORDER BY (title IS NOT NULL AND title LIKE 'Developer') DESC, playername ASC");
                $teamMembers = array();

                while ($row = $data->fetch_assoc()) {
                    $teamMembers[] = $row;
                }
            ?>
            <?php foreach($teamMembers as $teamMember): ?>
                <li>
                <a href="/profile/<?=$teamMember["profile_number"]; ?>"><?=$teamMember["playername"]; ?></a>: 
                <?php 
                    $labels = array();
                    if ($teamMember["title"] == 'Developer') {
                        $labels[] = 'Developer';
                    }

                    if ($teamMember["admin"]) {
                        $labels[] = 'Admin';
                    }

                    echo implode(", ", $labels);
                ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <h1 class="title">API</h1>
    <div class="container">
        A JSON representation of the current leaderboard status can be retrieved by appending '/json' to any page URL, i.e. <a href="/chamber/47458/json" class="unnamedURL"></a> or <a href="/profile/iVerb/json" class="unnamedURL"></a>.
    </div>

    <h2 class="subtitle">Libraries</h2>
    <div class="container">
        <table class="pointTable table table-condensed" style='margin-top: 20px; width: 160px'>
             <tr>
                <th>Name</th>
                <th>Language</th>
            </tr>
            <tr>
                <td><a href="https://github.com/NeKzor/Portal2Boards.Net">Portal2Boards.Net</a></td>
                <td>C#</td>
            </tr>
        </table>
    </div>

    <h1 class="title">Hosting</h1>
    <div class="container">
        <p>
        This site is currently hosted on <a href="https://www.fastcomet.com/">FastComet</a>.
        </p>
        <p>
        Demos are stored using <a href="https://www.google.com/drive/">Google Drive</a>. 
        The folder containg all demos can be found <a href="https://drive.google.com/folderview?id=<?=DemoManager::demoFolderId?>&usp=sharing">here</a>.
        </p>
    </div>

    <h1 class="title">Feature suggestions</h1>
    <div class="container">Forward any feature suggestions you may have to <a href="/profile/76561198047900528">iVerb</a>.</div>
</div>

<script>
    $("a.unnamedURL").each(function() {
        $(this).text(window.location.host + $(this).attr("href"));
    })
</script>