<div id="about">
    <h1 class="largeTitle">About</h1>

    <h1 class="title">Rules & console commands</h1>
    <div class="container">
    For rules and console commands, go <a href="https://rules.portal2.sr/" target="_blank">here</a>.
    </div>

    <h1 class="title">Point calculation</h1>
    <div class="container">
        Currently, the top <?=Leaderboard::numTrackedPlayerRanks?> times are tracked for each map.
        A player's points for a specific chamber is calculated as follows:
        Only the top <?=Leaderboard::rankForPoints?> get points.
        <style>
            table.fraction {
                font-size: 15px;
                color: inherit;
                margin: 15px;
            }
            table.fraction td.upper_line {
                border-top:solid 1px #555555;
            }
            table.fraction {
                text-align: center;
                vertical-align: middle;
                margin-top:0.5em; margin-bottom:0.5em; line-height: 1.6em;
            }
        </style>
        <table class="fraction" cellpadding="0" cellspacing="0">
            <tr>
                <td rowspan="2" nowrap="nowrap">
                    max[1,&nbsp;
                </td>
                <td nowrap="nowrap" style="font-size: 14px;">
                    (<?=Leaderboard::rankForPoints?> - (rank - 1))<sup>2</sup>
                </td>
                <td rowspan="2" nowrap="nowrap">
                    <!-- &nbsp;× (1 + (0.025 × bonus)  -->]
                </td>
            </tr>
            <tr>
                <td class="upper_line" style="font-size: 14px;">
                    <?=Leaderboard::rankForPoints?>
                </td>
            </tr>
        </table>

        This gives us the following:

        <style>
            .pointTable th {
                font-weight: 500;
                color: #555;
            }
            .pointTable td, .pointTable th {
                text-align: center;
            }
            .pointTable th:first-child, .pointTable td:first-child {
                border-right: 1px solid #ddd;
            }
        </style>
        <table class="pointTable table table-condensed" style='margin-top: 20px; width: 160px'>
            <tr>
                <th>Rank</th>
                <th>Points</th>
            </tr>
            <?php foreach(array(1, 5, 10, 20, 50, 100, 150, 200) as $rank): ?>
                <tr>
                    <td><?=$rank ?></td>
                    <td><?=ceil(Leaderboard::getPoints($rank))?></td>
                </tr>
            <?php endforeach; ?>
        </table>

        Note that points are displayed as whole numbers everywhere on the site by means of simple rounding.

    </div>

    <h1 class="title">Team</h1>
    <div class="container">
        <ul>
            <?php
                $data = Database::query("SELECT profile_number, IFNULL(boardname, steamname) as playername, title, admin FROM usersnew WHERE admin = 1 OR title = 'Developer' ORDER BY (title IS NOT NULL AND title LIKE 'Developer') DESC, playername ASC");
                $teamMembers = array();

                while ($row = $data->fetch_assoc()) {
                    $row["playername"] = htmlentities($row["playername"]);
                    $teamMembers[] = $row;
                }
            ?>
            <?php foreach($teamMembers as $teamMember): ?>
                <li>
                <a href="/profile/<?=$teamMember["profile_number"]; ?>"><?=$teamMember["playername"]; ?></a>: 
                <?php 
                    $labels = array();
                    if ($teamMember["title"] == 'Developer') {
                        $labels[] = 'Developer';
                    }

                    if ($teamMember["admin"]) {
                        $labels[] = 'Admin';
                    }

                    echo implode(", ", $labels);
                ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <h1 class="title">API</h1>
    <div class="container">
        A JSON representation of the current leaderboard status can be retrieved by appending '/json' to any page URL, i.e. <a href="/chamber/47458/json" class="unnamedURL"></a> or <a href="/profile/iVerb/json" class="unnamedURL"></a>.
    </div>

    <h2 class="subtitle">Libraries</h2>
    <div class="container">
        <table class="pointTable table table-condensed" style='margin-top: 20px; width: 160px'>
             <tr>
                <th>Name</th>
                <th>Language</th>
            </tr>
            <tr>
                <td><a href="https://github.com/NeKzor/Portal2Boards.Net" target="_blank">Portal2Boards.Net</a></td>
                <td>C#</td>
            </tr>
        </table>
    </div>

    <h1 class="title">Hosting</h1>
    <div class="container">
        <p>
        This site is currently hosted on <a href="https://hetzner.cloud/?ref=LSfkawynXCD3" target="_blank">Hetzner</a>.
        </p>
        <p>
        Demos are stored using Hetzner Storage Box.
        The folder containg all demos can be accessed on the following rsync address:
        <code>rsync://board.portal2.sr:/demos</code>
        </p>
    </div>

</div>

<script>
    $("a.unnamedURL").each(function() {
        $(this).text(window.location.host + $(this).attr("href"));
    })
</script>
