<?php include("util/PageGenerator.php") ?>
<?php include("util/ChangelogView.php") ?>
<?php $mapInfo = $GLOBALS["mapInfo"]; ?>

<?php function filterActivity($change) { return $change["time_gained"] != NULL && $change["banned"] != 1; } ?>
<?php $activity = array_values(array_filter($view->changelog, "filterActivity")) ?>
<?php //$activity = array_values($view->changelog) ?>

<script>
    $("body").css("min-width", "1335px");
</script>

<div id="changelog">
    <div id="filters">
        <div id="filter_instructions_lol">Use these filters to display the changelog you want</div>
        <div id="filter_options">
            <form name="filters" action="/changelog" method="get">
                <div class="changelog-filter-options-wrapper">
                    <div class="changelog-filter-options-name changelog-filter-options-group">
                        <div style="float: left;" class="input">
                            <label for="boardName">Nickname</label>
                            <input type="text" id="boardName" name="boardName" value="<?=htmlspecialchars($param['boardName']);?>">
                        </div>
                        <div style="float: left;" class="input">
                            <label for="profileNumber">Steam profile number</label>
                            <input type="text" id="profileNumber" name="profileNumber" value="<?=htmlspecialchars($param['profileNumber']);?>">
                        </div>
                    </div>
                    <div class="changelog-filter-options-chamber changelog-filter-options-group">
                        <div style="float: left;" class="input">
                            <label for="chapter">Chapter name</label>
                            <select style="width: 100%;" id="chapter" name="chapter">
                                <option value="">No chapter</option>
                                <?php foreach(array("sp" => "Single Player", "coop" => "Cooperative") as $modeId => $mode): ?>
                                    <option disabled><?=$mode?></option>
                                    <?php foreach($mapInfo["modes"][$modeId] as $chapterId): ?>
                                        <?php $chapterName = $mapInfo["chapters"][$chapterId]["chapterName"]?>
                                        <option value="<?=$chapterId?>" <?php if($param['chapter'] == $chapterId) : ?>selected<?php endif; ?>>&nbsp;&nbsp;<?=$chapterName?></option>
                                    <?php endforeach; ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div style="float: left;" class="input">
                            <label for="chamber-name">Chamber name</label>
                            <select style="width: 100%;" id="chamber-name" name="chamber">
                                <option value="">No chamber</option>
                                <?php foreach(array("sp" => "Single Player", "coop" => "Cooperative") as $modeId => $mode): ?>
                                    <option disabled><?=$mode?></option>
                                    <?php foreach($mapInfo["modes"][$modeId] as $chapterId): ?>
                                        <option disabled>&nbsp;&nbsp;<?=$mapInfo["chapters"][$chapterId]["chapterName"]?></option>
                                        <?php foreach($mapInfo["chapters"][$chapterId]["maps"] as $mapId): ?>
                                            <?php $mapName = $mapInfo["maps"][$mapId]["mapName"]?>
                                            <option value="<?=$mapId?>" <?php if($param['chamber'] == $mapId): ?>selected<?php endif; ?>>&nbsp;&nbsp;&nbsp;&nbsp;<?=$mapName?></option>
                                        <?php endforeach; ?>
                                    <?php endforeach; ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="changelog-filter-options-date changelog-filter-options-group">
                        <div style="float: left;" class="input">
                            <label for="startDate">Start Date</label>
                            <input type="date" id="startDate" name="startDate" value="<?=htmlspecialchars($param['startDate']);?>">
                        </div>
                        <div style="float: left;" class="input">
                            <label for="endDate">End Date</label>
                            <input type="date" id="endDate" name="endDate" value="<?=htmlspecialchars($param['endDate']);?>">
                        </div>
                    </div>
                    <div class="changelog-filter-options-rank changelog-filter-options-group">
                        <div style="float: left;" class="input">
                            <label for="startRank">Start Rank</label>
                            <input type="number" min="0" id="startRank" name="startRank" value="<?=htmlspecialchars($param['startRank']);?>">
                        </div>
                        <div style="float: left;" class="input">
                            <label for="endRank">End Rank</label>
                            <input type="number" min="1" id="endRank" name="endRank" value="<?=htmlspecialchars($param['endRank']);?>">
                        </div>
                    </div>
                    <div style="float: left;" class="check">
                        <div style="position: relative;">Single Player</div>
                        <div class="checkbox <?php if($param['sp'] == "1"): ?>ticked<?php endif; ?>"></div>
                        <input type="hidden" value="<?=htmlspecialchars($param['sp']);?>" name="sp">
                    </div>
                    <div style="float: left;" class="check">
                        <div style="position: relative;">Cooperative</div>
                        <div class="checkbox <?php if($param['coop'] == "1"): ?>ticked<?php endif; ?>"></div>
                        <input type="hidden" value="<?=htmlspecialchars($param['coop']);?>" name="coop">
                    </div>
                    <div style="float: left;" class="check">
                        <div style="position: relative;">World Record</div>
                        <div class="checkbox <?php if($param['wr'] == "1"): ?>ticked<?php endif; ?>"></div>
                        <input type="hidden" value="<?=htmlspecialchars($param['wr']);?>" name="wr">
                    </div>
                    <div style="float: left;" class="check">
                        <div style="position: relative;">Demo</div>
                        <div class="checkbox <?php if($param['demo'] == "1"): ?>ticked<?php endif; ?>"></div>
                        <input type="hidden" value="<?=htmlspecialchars($param['demo']);?>" name="demo">
                    </div>
                    <div style="float: left;" class="check">
                        <div style="position: relative;">Video</div>
                        <div class="checkbox <?php if($param['yt'] == "1"): ?>ticked<?php endif; ?>"></div>
                        <input type="hidden" value="<?=htmlspecialchars($param['yt']);?>" name="yt">
                    </div>
                    <div style="float: left;" class="check">
                        <div style="position: relative;">Submission</div>
                        <div class="checkbox <?php if($param['submission'] == "1"): ?>ticked<?php endif; ?>"></div>
                        <input type="hidden" value="<?=htmlspecialchars($param['submission']);?>" name="submission">
                    </div>
                    <div style="float: left;" class="check">
                        <div style="position: relative;">Pending</div>
                        <div class="checkbox <?php if($param['pending'] == "1"): ?>ticked<?php endif; ?>"></div>
                        <input type="hidden" value="<?php if($param['pending'] == "1"): ?>2<?php endif; ?>" name="pending">
                    </div>
                    <!--                <div style="float: left; display: none" class="number">-->
                    <!--                    <label class="top" style="position: relative;">Max days ago</label>-->
                    <!--					<label class="bottom" style="position: relative;">Unlimited: 0</label>-->
                    <!--                    <input type="number" value="--><?//=$param['maxDaysAgo'];?><!--" name="maxDaysAgo">-->
                    <!--                </div>-->
                    <div style="float: right; margin: 24px 20px 0px 0px">
                        <input type="submit" value="Filter"></input>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <?php if (count($activity) > 0): ?>
        <div class = 'activity'>
            <div id= 'changelogActivity' style= 'height: 175px;'>
                <i class="fa fa-circle-o-notch fa-spin fa-fw loading"></i>
            </div>
        </div>
    <?php endif; ?>

    <?php if (count($view->changelog) == 0): ?>
        <div style="font-size: 20px; margin: auto; width: 100%; text-align: center; color: #888;">
            <i class="fa fa-times" style="padding-right: 10px"></i>No scores found
        </div>
    <?php else: ?>
        <div id="entries">
            <div class="controls">
                <div class="button previous">
                    <!--				<span class="name">Newer</span>-->
                    <span class="icon"><i class="fa fa-caret-left fa-3x" aria-hidden="true"></i></span>
                </div>
                <span class="currentPageLabel"></span>
                <div class="button next">
                    <span class="icon"><i class="fa fa-caret-right fa-3x" aria-hidden="true"></i></span>
                    <!--				<span class="name">Older</span>-->
                </div>
            </div>
            <div id="firstentry">
                <div class="date">Date</div>
                <div class="profileIcon"></div>
                <div class="boardname">Player</div>
                <div class="map">Map</div>
                <div class="chapter">Chapter</div>
                <div class="previousscore">Previous score</div>
                <div class="newscore">New score</div>
                <div class="improvement">Improvement</div>
                <div class="demo-url"></div>
                <div class="youtube"></div>
                <div class="submission"></div>
                <div class="submission"></div>
                <div class="banScore"><?php if (SteamSignIn::loggedInUserIsAdmin()): ?><?php endif; ?></div>
            </div>
            <div id="otherentries">
                <?php PageGenerator::generatePages($view->changelog, array("ChangelogView", "getEntry")); ?>
            </div>
        </div>
    <?php endif; ?>
    </div>
<script>

    $(document).ready(function() {

        $(".entry").each(function() {
            
            var $entry = $(this);
            var $preRank = $entry.find(".previousscore .rank");
            var $postRank = $entry.find(".newscore .rank");
            var $rankDiff = $entry.find(".rankImprovement")
            
            var preRank = $preRank.find("i").length == 1 ? 1 : parseInt($preRank.text());
            var postRank = $postRank.find("i").length == 1 ? 1 : parseInt($postRank.text());

            pointsOnHover($preRank, preRank);
            pointsOnHover($postRank, postRank);

            var prePoints = getPointsFromRank(preRank);
            var postPoints = getPointsFromRank(postRank)
            var pointDiff = (postPoints - prePoints);

            if (!isNaN(pointDiff) && pointDiff != 0) {
                pointDiff = Math.round(pointDiff * 10) / 10;
                var title = "gained " + pointDiff + " " + (pointDiff == 1 ?  + "point" : "points");
                $rankDiff.tooltip({trigger: 'manual', title: title });
                $rankDiff.hover(function() {
                    $(this).tooltip('show');
                }, function() {
                    $(this).tooltip('hide');
                });
            }
        });

        $(".checkbox").click(function() {
            $(this).toggleClass("ticked");
            var v = $(this).parent().find("input:eq(0)").val();
            v = (v == 0 ? "1" : "");
            $(this).parent().find("input:eq(0)").val(v);
        });

        $(".entry .date").each(function() {
            var $dateTime = $(this).find(".dateTime");
            var $dateDifference = $(this).find(".dateDifference");

            var date = $(this).attr("date");
            if (date !== undefined && date !== "" && date !== null) {
                formatDateDifferenceFromNow($dateDifference, date, true);
                $dateTime.text(localizeDate(date, "ddd, YYYY-MM-DD, HH:mm:ss"));
            }
            else {
                $dateTime.text("Unknown");
            }
        });

        $(".controls .next").click(function() {
            var page = nextPage($(".entries"));
            var lastPage = getLastPage($(".entries"));
            $(".currentPageLabel").text(page + " / " + lastPage);
        });

        $(".controls .previous").click(function() {
            var page = previousPage($(".entries"));
            var lastPage = getLastPage($(".entries"));
            $(".currentPageLabel").text(page + " / " + lastPage);
        });

        var lastPage = getLastPage($(".entries"));
        $(".currentPageLabel")
            .text(Math.min(1, lastPage) + " / " + lastPage)
            .css("width", 20 + (2 * (Math.floor(Math.log(Math.max(2, lastPage)) / Math.LN10) + 1) * 7));

        //$("#otherentries").css("height", Math.min(25, <?=count($view->changelog)?>) * 42);

        $(".rank").each(function() {
            drawRank($(this));
        });

        var activityByScore = getActivityByScore(<?=json_encode($activity)?>);
        if (Object.keys(activityByScore).length > 0) {
            let activityByDate = getActivityByDate(activityByScore);
            const urlParams = new URLSearchParams(window.location.search);
            let endDate = (urlParams.get("endDate") ?? '') !== ''  ? urlParams.get("endDate") : getCurrentLocalDate();
            let startDate = (urlParams.get("startDate") ?? '') !== ''  ? urlParams.get("startDate") : localizeDate(getDateFirstChange(activityByDate));
            drawActivityChart(activityByDate, startDate, endDate, $("#changelogActivity"));
        }
    });

    function setBannedStatus(id, banStatus, clickEventTarget) {
        $.ajax({
            url: '/setScoreBanStatus',
            type: 'POST',
            success: function (data) {
                var parent = $(clickEventTarget).parent().parent();
                var oldDiv = (banStatus == 1) ? parent.find(".ban") : parent.find(".unban");
                var newDiv = (banStatus == 0) ? parent.find(".ban") : parent.find(".unban");
                newDiv.show();
                oldDiv.hide();
            },
            data: {
                id: id,
                banStatus: banStatus
            }
        });
    }

</script>
