<style>
    .profileIcon img {
        border-radius: 20px;
        max-height: 35px;
    }

    .profileIcon, .boardname {
        display: inline-block;
        vertical-align: top;
    }

    .profileIcon {
        margin-right: 15px;
    }

    .boardname, .donationAmount {
        width: 200px;
        font-family: Aperture;
        font-size: 16px;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        line-height: 35px;
    }

    .goodUser > td {
        padding-bottom: 9px;
    }
</style>

<div id="about">
    <h1 class="largeTitle">Donators</h1>
    <div style="margin-left: 20px; margin-top: 20px">
        <table>
        <?php foreach($view->donators as $user): ?>
            <tr class="goodUser">
                <td class="profileIcon">
                    <a href="/profile/<?=$user["profile_number"]; ?>">
                        <img src="<?=$user["avatar"]; ?>" alt=""/>
                    </a>
                </td>
                <td class="boardname">
                    <a href="/profile/<?= $user["profile_number"]; ?>"><?= $user["playername"] ?></a>
                </td>
                <td class="donationAmount">
                    € <?= $user["donation_amount"] ?>
                </td>
            </tr>            
        <?php endforeach ?>
        </table>
    </div>
</div>