<div id="editProfile">
    <div class="titleContainer">
        <h1 class="title">Profile</h1>
        <h1 class="subtitle">Edit your profile</h1>
    </div>
    <div class="normalcontent">
        <form action="/editprofile" method="post">
            <label for="twitch">Twitch username</label>
            <input type="text" id="twitch" name="twitch" value="<?=$loggedInUser->userData->twitch;?>"/>
            <label for="youtube">Youtube channel URL / user name</label>
            <input type="text" id="youtube" name="youtube" value="<?=($loggedInUser->userData->youtube != NULL) ? "www.youtube.com".$loggedInUser->userData->youtube : ""?>"/>
            <label for="youtube">Board name (Keep empty to remain synced with your steam nickname)</label>
            <input type="text" id="boardname" name="boardname" value="<?=$loggedInUser->userData->boardname;?>"/>
            <button class="button" type="submit">Save</button>
        </form>
    </div>
    <?php if(isset($view->msg)): ?>
        <div><?=$view->msg?></div>
    <?php endif; ?>

    <div class="auth_hash" style="display: flex; gap: 1rem;">
        <p>Auth Hash: <?=$loggedInUser->userData->auth_hash;?></p>
        <button class="button btn" data-clipboard-text="<?=$loggedInUser->userData->auth_hash;?>" style="margin: 0 0 10px;">Copy</button>
        <button class="button regen-btn" style="margin: 0 0 10px;">Regenerate</button>
    </div>
</div>

<script>
    new ClipboardJS('.btn');

    $('.regen-btn').click(function() {
        $.ajax({
            type: "POST",
            data: "null",
            url: "/regenerateAuthHash",
        }).done(function( msg ) {
            location.reload();
        });
    });
</script>