<?php $cookieName = "site-notification-16-11-2017"; ?>
<?php $giveAnnouncement = false; ?>

<?php if(!isset($_COOKIE[$cookieName]) && $giveAnnouncement): ?>

    <div id="announcement">
        <span class="notification">
            <b>Announcement:</b> We are currently experiencing issues syncing with the Steam leaderboards. If your score is not showing up, please submit it via your profile.
        </span>
        <span class="close-btn"></span>
    </div>

    <script>
        $(document).ready(function() {
            setTimeout(function() {
                $("#announcement").slideDown("slow");
            }, 2000);

            $("#announcement .close-btn").click(function() {
                $("#announcement").slideUp("slow");
                var d = new Date();
                d.setTime(d.getTime() + (10 * 365 * 24 * 60 * 60 * 1000)); //10 years
                var expires = "expires="+d.toGMTString();
                document.cookie = "<?=$cookieName?>=yes; " + expires;
            });
        });
    </script>

<?php endif; ?>