<?php $cookieName = "site-notification-02-10-2017"; ?>
<?php $giveAnnouncement = true; ?>

<?php if(!isset($_COOKIE[$cookieName]) && $giveAnnouncement): ?>

    <div id="announcement">
        <span class="notification">
            <b>Announcement:</b> Thanks to everyone for donating to cover the yearly server costs! You guys are not only fast in Portal 2, but also in raising funds. We met the donation goal in under half an hour!
        </span>
        <span class="close-btn"></span>
    </div>

    <script>
        $(document).ready(function() {
            setTimeout(function() {
                $("#announcement").slideDown("slow");
            }, 2000);

            $("#announcement .close-btn").click(function() {
                $("#announcement").slideUp("slow");
                var d = new Date();
                d.setTime(d.getTime() + (10 * 365 * 24 * 60 * 60 * 1000)); //10 years
                var expires = "expires="+d.toGMTString();
                document.cookie = "<?=$cookieName?>=yes; " + expires;
            });
        });
    </script>

<?php endif; ?>