<div class="donationProgress">
    <div class="donationTitle"><a href="http://fnd.us/board.iverb.me" target="_blank">Server Costs 2017 $50</a></div>
    <div class="donationInfo">
      <div class="fr-widget" data-type="badge" data-variant="wide" data-width="340" data-url="http://fnd.us/board.iverb.me"><a href="https://fundrazr.com" target="_blank"><img src="//d30pl5hav4s8uw.cloudfront.net/widgets/powered-by.png" alt="Powered by FundRazr" /></a></div>
    </div>
</div>

<script>(function() { 
  var d = document, fr = d.createElement('script');
  fr.type = 'text/javascript';
  fr.async = true; fr.src = ((d.location.protocol.indexOf('https') == 0)? 'https://s-' : 'http://') + 'static.fundrazr.com/widgets/loader.js'; 
  var s = d.getElementsByTagName('script')[0]; s.parentNode.insertBefore(fr, s);})();
</script>

<script>
    // $(document).ready(function() {
    //   setTimeout(function() {
    //     $(".donationProgress").fadeIn("1200");
    //   }, 2000);
    // });
</script>


<style>

  .donationProgress{
    position: absolute;
    top: 17px;
    left: 690px;
    /* width: 199px; */
    /* background-color: #222; */
  }

  .donationTitle {
    display: inline-block;
    text-align: center;
    font-weight: 500;
    font-family: Segoe UI;
    font-size: 14px;
    color: #3d3d3d;    
    margin-right: 9px;
    width: 72px;
    position: relative;
    top: 5px;
  }

  .donationInfo {
    display: inline-block;
    top: 8px;
    position: relative;
    overflow: hidden;
    width: 170px;
    height: 55px;
    padding-bottom: 20px;
    border-radius: 5px;
  }

  .donationInfo iframe {
    position: absolute;
    left: -170px;
    top: -115px;
  }

</style>