<!DOCTYPE>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title><?php echo $view->siteTitle . View::$pageData["pageTitle"]; ?></title>

        <?php foreach($view->css as $path): ?>
            <link rel="stylesheet" type="text/css" href="<?=$path; ?>?v=<?=$view->browserCacheVersion; ?>">
        <?php endforeach; ?>

        <?php foreach($view->js as $path): ?>
            <script type="text/javascript" src="<?=$path; ?>"></script>
        <?php endforeach; ?>

        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-82886060-1', 'auto');
          ga('send', 'pageview');
        </script>
		
		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-99XV1V9EGG"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'G-99XV1V9EGG');
		</script>
    </head>

    <body>
        <div id="wrapper">

            <?php include("announcement.phtml"); ?>
            
            <div id="header">
                <div id="header_left">
                    <h2 id="sitetitle">Portal 2 Leaderboards</h2>
                    <div id="navigation">
                        <?php include("navigation.phtml"); ?>
                    </div>
                    <?php //include("donation.phtml"); ?>
                </div>
                <div id="header_right">
                    <div id="userinfo">
                        <?php include("userinfo.phtml"); ?>
                    </div>
                </div>
            </div>
            <?php include("message.phtml"); ?>
            <div id="content">
                <?php
                    if(isset(View::$pageData["contentTemplate"])) {
                        require_once(__DIR__."/../".View::$pageData["contentTemplate"]);
                    }
                ?>
            </div>
            <div class="push"></div>
        </div>
        <?php include("footer.phtml"); ?>
    </body>

</html>
