<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta
            http-equiv="Content-Security-Policy"
            content="
                default-src 'self';
                script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;
                style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;
                font-src 'self' https://cdnjs.cloudflare.com;
                frame-src https://www.youtube.com;
                img-src 'self' https://*;
            "
        />
        <meta name="referrer" content="no-referrer" />

        <title><?php echo $view->siteTitle . View::$pageData["pageTitle"]; ?></title>

        <?php foreach($view->css as [$path, $hash]): ?>
            <link rel="stylesheet" type="text/css" href="<?=$path; ?>?v=<?=$view->browserCacheVersion; ?>"<?php echo isset($hash) ? " integrity=\"$hash\" crossorigin=\"anonymous\"" : '' ?>>
        <?php endforeach; ?>

        <?php foreach($view->js as [$path, $hash]): ?>
            <script type="text/javascript" src="<?=$path; ?>"<?php echo isset($hash) ? " integrity=\"$hash\" crossorigin=\"anonymous\"" : '' ?>></script>
        <?php endforeach; ?>

        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    </head>

    <body>
        <div id="wrapper">

            <?php include("announcement.phtml"); ?>
            
            <div id="header">
                <div id="header_left">
                    <h2 id="sitetitle">Portal 2 Leaderboards</h2>
                    <div id="navigation">
                        <?php include("navigation.phtml"); ?>
                    </div>
                    <?php //include("donation.phtml"); ?>
                </div>
                <div id="header_right">
                    <div id="userinfo">
                        <?php include("userinfo.phtml"); ?>
                    </div>
                </div>
            </div>
            <?php include("message.phtml"); ?>
            <div id="content">
                <?php
                    if(isset(View::$pageData["contentTemplate"])) {
                        require_once(__DIR__."/../".View::$pageData["contentTemplate"]);
                    }
                ?>
            </div>
            <div class="push"></div>
        </div>
        <?php include("footer.phtml"); ?>
    </body>

</html>
