<?php $mapInfo = Cache::get("maps") ?>
<a href="/changelog" class="nav_button">
    <div id="time_icon" class="nav_icon"></div>
    <div class="btnLabel">Score Updates</div>
</a>
<a href="/chambers/sp" class="nav_button">
    <div id="sp_icon" class="nav_icon"></div>
    <div class="btnLabel">Single Player</div>
</a>
<a href="/chambers/coop" class="nav_button">
    <div id="coop_icon" class="nav_icon"></div>
    <div class="btnLabel">Cooperative</div>
</a>
<div class="nav_dropdown">
    <div id="cube_icon" class="nav_icon"></div>
    <div class="btnLabel">Aggregated</div>
    <ul style="width:140px">
      <li>
          <a href="/aggregated/overall" style="height: 29px">
            <div class="nav_icon" style="background: url('/images/cup_noborder.jpg'); background-size: 29px 29px;"></div>
            <div class="btnLabel">Overall</div>
          </a>
      </li>
      <li class="nav_dropdown">
          <div style="height: 29px">
              <div class="nav_icon" style="background: url('/images/sp_noborder.jpg'); background-size: 29px 29px;"></div>
              <div class="btnLabel">Single Player</div>
          </div>
          <ul style="width:165px">
              <li>
                <a href="/aggregated/sp">
                    <div class="nav_icon"><i class="fa fa-star" aria-hidden="true"></i></div>
                    <div class="btnLabel">Total</div>
                </a>
              </li>
              <?php $i = 1; foreach ($mapInfo["modes"]["sp"] as $chapter): ?>
                  <li>
                      <a href="/aggregated/chapter/<?=$chapter?>">
                        <div class="nav_icon"><?=$i?></div>
                        <div class="btnLabel"><?=$mapInfo["chapters"][$chapter]["chapterName"]?> </div>
                      </a>
                  </li>
              <?php $i++; endforeach; ?>
          </ul>
      </li>
      <li class="nav_dropdown">
          <div style="height: 29px">
              <div class="nav_icon" style="background: url('/images/coop_noborder.jpg'); background-size: 29px 29px;"></div>
              <div class="btnLabel">Cooperative</div>
          </div>
          <ul style="width:185px">
              <li>
                  <a href="/aggregated/coop">
                      <div class="nav_icon"><i class="fa fa-star" aria-hidden="true"></i></div>
                      <div class="btnLabel">Total</div>
                  </a>
              </li>
              <?php $i = 1; foreach ($mapInfo["modes"]["coop"] as $chapter): ?>
                  <li>
                      <a href="/aggregated/chapter/<?=$chapter?>">
                        <div class="nav_icon"><?=$i?></div>
                        <div class="btnLabel"><?=$mapInfo["chapters"][$chapter]["chapterName"]?></div>
                      </a>
                  </li>
              <?php $i++; endforeach; ?>
          </ul>
      </li>
    </ul>
</div>

<style>
  .donator_icon {
      background: url('/images/cakeicon.png');
      background-position: center;
      background-size: 25px 25px !important;
      width: 25px !important;
      height: 25px !important;
      margin: 2px;
  }
</style>

<div class="nav_dropdown">
    <div id="aperture_icon" class="nav_icon"></div>
    <div class="btnLabel">More</div>
    <ul style="width:145px">
      <li class="nav_dropdown">
          <a href="https://www.speedrun.com/Portal_2" target="_blank" style="height: 29px">
              <div class="nav_icon" style="background: url('/images/running.png'); background-size: 29px 29px;"></div>
              <div class="btnLabel">Full Game Runs</div>
          </a>          
      </li>
      <li class="nav_dropdown">
          <a href="https://discordapp.com/invite/hRwE4Zr" target="_blank" style="height: 29px">
              <div class="nav_icon" style="background: url('/images/discord_noborder.png'); background-size: 29px 29px;"></div>
              <div class="btnLabel">Discord</div>
          </a>          
      </li>
        <li class="nav_dropdown">
          <a href="https://github.com/p2sr/Portal2Boards" target="_blank" style="height: 29px">
              <div class="nav_icon" style="background: url('/images/github.png'); background-size: 29px 29px;"></div>
              <div class="btnLabel">GitHub</div>
          </a>          
      </li>
      <li>
          <a href="/donators" style="height: 29px">
            <div class="nav_icon donator_icon"></div>
            <div class="btnLabel">Donators</div>
          </a>
      </li>
      <li>
          <a href="/wallofshame" style="height: 29px">
            <div class="nav_icon" style="background: url('/images/wallofshame.png'); background-size: 29px 29px;"></div>
            <div class="btnLabel">Wall of Shame</div>
          </a>
      </li>
      <li>
          <a href="/about" style="height: 29px">
            <div class="nav_icon" style="background: url('/images/cupcake.png'); background-size: 29px 29px;"></div>
            <div class="btnLabel">About</div>
          </a>
      </li>
    </ul>
</div>

<!--<div class="nav_dropdown">-->
<!--    <div id="lp_icon" class="nav_icon"></div>-->
<!--    <div class="label">Least Portals</div>-->
<!--    <ul style="width:150px">-->
<!--        <li>-->
<!--            <a href="/lp/sp" style="height: 29px">-->
<!--                <div class="nav_icon" style="background: url('/images/sp_noborder.jpg'); background-size: 29px 29px;"></div>-->
<!--                <div class="label">Single Player</div>-->
<!--            </a>-->
<!--        </li>-->
<!--        <li>-->
<!--            <a href="/lp/coop" style="height: 29px">-->
<!--                <div class="nav_icon" style="background: url('/images/coop_noborder.jpg'); background-size: 29px 29px;"></div>-->
<!--                <div class="label">Cooperative</div>-->
<!--            </a>-->
<!--        </li>-->
<!--    </ul>-->
<!--</div>-->

<!--<a href="/lp" class="nav_button">-->
<!--    <div id="lp_icon" class="nav_icon"></div>-->
<!--    <div class="label">Least Portals</div>-->
<!--</a>-->

<!-- <a href="/about" class="nav_button">
    <div id="aperture_icon" class="nav_icon"></div>
    <div class="btnLabel">About</div>
</a> -->


<script>

    // $(".nav_dropdown").click(function(event) {
    //
    //     var $dropDownContent = $(this).find("> ul");
    //     var isVisible = $dropDownContent.css("visibility") == "visible";
    //
    //     if (!isVisible) {
    //         //$dropDownContent.css("visibility", "visible");
    //         $dropDownContent.addClass("clicked");
    //     }
    //     else if ($dropDownContent.hasClass("clicked")) {
    //         $(this).parent().find(".nav_dropdown ul").css("visibility", "hidden");
    //         $dropDownContent.css("visibility", "hidden");
    //         $dropDownContent.removeClass("clicked");
    //     }
    //
    //     event.stopPropagation();
    // });

    $(".nav_dropdown").hover(function(event) {
        var $dropDownContent = $(this).find("> ul");
        $dropDownContent.css("visibility", "visible");
        
    }, function(event) {
        $(this).find("ul").css("visibility", "hidden");
    });

</script>